site :opscode

cookbook 'apt',        '~> 2.3.4'
cookbook 'ark',        '~> 0.4.2'
cookbook 'dev_env-bootstrap',
  path: 'cookbooks/dev_env-bootstrap'
cookbook 'git',        '~> 2.9.0'
cookbook 'packer',     '~> 0.2.4'
cookbook 'rbenv',
  git: 'git://github.com/fnichol/chef-rbenv.git', branch: 'v0.7.2'
cookbook 'ruby_build', '~> 0.8.0'
cookbook 'vagrant',    '~> 0.2.0'
cookbook 'virtualbox', '~> 1.0.2'
