# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-berkshelf"
Vagrant.require_plugin "vagrant-omnibus"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "zerg_dev"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder "..", "/zerg"

  # Enabling vagrant-berkshelf & vagrant-omnibus plugins
  config.berkshelf.enabled    = true
  config.omnibus.chef_version = :latest

  config.vm.provider :virtualbox do |vb|
    # boot with headless mode
    vb.gui = false
    vb.name = "zerg_dev"
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  config.vm.provision :chef_solo do |chef|
      chef.add_recipe "apt"
      chef.add_recipe "ark"
      chef.add_recipe "dev_env-bootstrap"
      chef.add_recipe "virtualbox"
      chef.add_recipe "vagrant"
      chef.add_recipe "packer"
      chef.add_recipe "git"
      chef.add_recipe "ruby_build"
      chef.add_recipe "rbenv::vagrant"
      chef.add_recipe "rbenv::user"
  
      # You may also specify custom JSON attributes:
      chef.json = { 
        "rbenv" => {
          "user_installs" => [{
            "user" => "vagrant",
            "rubies" => [ "1.9.3-p484" ],
            "global" =>   "1.9.3-p484",
            "gems"   => {
              "1.9.3-p484" => [{ "name" => "bundler" }]
            }
          }]
        },
        "packer" => {
          "version" => "0.5.1"
        },
        "vagrant" => {
          "url" => "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.4.3_x86_64.deb",
          "checksum" => "dbd06de0f3560e2d046448d627bca0cbb0ee34b036ef605aa87ed20e6ad2684b",
          "plugins" => ["vagrant-aws", "vagrant-libvirt", "vagrant-mutate"]
        },
        "virtualbox" => {
          "version" => "4.3"
        } 
      }
  end
end
